// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dnWalker.TestGenerator.XunitFramework
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using dnWalker.TestGenerator.TestProjects;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class XunitTestProjectTemplate : XunitTestProjectTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 8 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
 ITestProjectContext context = Context; 
            
            #line default
            #line hidden
            this.Write("\r\n<Project Sdk=\"Microsoft.NET.Sdk\">\r\n\r\n    <PropertyGroup>\r\n");
            
            #line 13 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	if (context.Targets.Count == 0)
	{

            
            #line default
            #line hidden
            this.Write("        <TargetFramework>");
            
            #line 17 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FallbackTargetFramework));
            
            #line default
            #line hidden
            this.Write("</TargetFramework>\r\n");
            
            #line 18 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}
	else if (Context.Targets.Count == 1)
	{

            
            #line default
            #line hidden
            this.Write("        <TargetFramework>");
            
            #line 23 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(context.Targets[0]));
            
            #line default
            #line hidden
            this.Write("</TargetFramework>\r\n");
            
            #line 24 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("        <TargetFrameworks>");
            
            #line 29 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(context.Targets)));
            
            #line default
            #line hidden
            this.Write("</TargetFrameworks>\r\n");
            
            #line 30 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("        <IsPackable>false</IsPackable>\r\n        <Nullable>");
            
            #line 34 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(context.NullableEnable ? "enable" : "disable"));
            
            #line default
            #line hidden
            this.Write("</Nullable>\r\n    </PropertyGroup>\r\n\r\n");
            
            #line 37 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
 
	// package references 
	if (BasePackages.Count > 0 || context.PackageReferencies.Count > 0)
	{

            
            #line default
            #line hidden
            this.Write("    <ItemGroup>\r\n");
            
            #line 43 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		foreach (PackageReference p in BasePackages)
		{
			WritePackageReference(p);
		}

            
            #line default
            #line hidden
            
            #line 49 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		foreach (PackageReference p in context.PackageReferencies)
		{
			WritePackageReference(p);
		}

            
            #line default
            #line hidden
            this.Write("    </ItemGroup>\r\n\r\n");
            
            #line 57 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}

	// project references
	if (context.ProjectReferencies.Count > 0)
	{

            
            #line default
            #line hidden
            this.Write("    <ItemGroup>\r\n");
            
            #line 65 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		foreach (string project in context.ProjectReferencies)
		{
			WriteProjectReference(project);
		}

            
            #line default
            #line hidden
            this.Write("    </ItemGroup>\r\n\r\n");
            
            #line 73 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}
	// service references
	if (BaseServices.Count > 0 || context.Services.Count > 0)
	{

            
            #line default
            #line hidden
            this.Write("    <ItemGroup>\r\n");
            
            #line 80 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		foreach (Guid s in BaseServices)
		{
			WriteServiceReference(s);
		}

            
            #line default
            #line hidden
            
            #line 86 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		foreach (Guid s in context.Services)
		{
			WriteServiceReference(s);
		}

            
            #line default
            #line hidden
            this.Write("    </ItemGroup>\r\n");
            
            #line 93 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("</Project>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 97 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	private static string JoinTokens(IEnumerable<string> tokens)
	{
		return string.Join("; ", tokens);
	}

        
        #line default
        #line hidden
        
        #line 103 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	private void WritePackageReference(PackageReference p)
	{

        
        #line default
        #line hidden
        
        #line 106 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("        <PackageReference Include=\"");

        
        #line default
        #line hidden
        
        #line 107 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 107 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("\" Version=\"");

        
        #line default
        #line hidden
        
        #line 107 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Version));

        
        #line default
        #line hidden
        
        #line 107 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("\"");

        
        #line default
        #line hidden
        
        #line 107 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		if (p.IncludeAssets.Count > 0 || p.ExcludeAssets.Count > 0 || p.PrivateAssets.Count > 0)
		{

        
        #line default
        #line hidden
        
        #line 110 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(">\r\n");

        
        #line default
        #line hidden
        
        #line 111 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

			if (p.IncludeAssets.Count > 0)
			{

        
        #line default
        #line hidden
        
        #line 114 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("            <IncludeAssets>");

        
        #line default
        #line hidden
        
        #line 115 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(p.IncludeAssets)));

        
        #line default
        #line hidden
        
        #line 115 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("</IncludeAssets>\r\n");

        
        #line default
        #line hidden
        
        #line 116 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

			}
			if (p.ExcludeAssets.Count > 0)
			{

        
        #line default
        #line hidden
        
        #line 120 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("            <ExcludeAssets>");

        
        #line default
        #line hidden
        
        #line 121 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(p.ExcludeAssets)));

        
        #line default
        #line hidden
        
        #line 121 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("</ExcludeAssets>\r\n");

        
        #line default
        #line hidden
        
        #line 122 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

			}
			if (p.PrivateAssets.Count > 0)
			{

        
        #line default
        #line hidden
        
        #line 126 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("            <PrivateAssets>");

        
        #line default
        #line hidden
        
        #line 127 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(p.PrivateAssets)));

        
        #line default
        #line hidden
        
        #line 127 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("</PrivateAssets>\r\n");

        
        #line default
        #line hidden
        
        #line 128 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

			}

        
        #line default
        #line hidden
        
        #line 130 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("        </PackageReference>\r\n");

        
        #line default
        #line hidden
        
        #line 132 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		}
		else
		{

        
        #line default
        #line hidden
        
        #line 136 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(" />\r\n");

        
        #line default
        #line hidden
        
        #line 137 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

		}
	}

        
        #line default
        #line hidden
        
        #line 141 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	private void WriteProjectReference(string project)
	{

        
        #line default
        #line hidden
        
        #line 144 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("        <ProjectReference Include=\"");

        
        #line default
        #line hidden
        
        #line 145 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(project));

        
        #line default
        #line hidden
        
        #line 145 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("\" />\r\n");

        
        #line default
        #line hidden
        
        #line 146 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}

        
        #line default
        #line hidden
        
        #line 149 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	private void WriteServiceReference(Guid serviceGuid)
	{

        
        #line default
        #line hidden
        
        #line 152 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("        <Service Include=\"{");

        
        #line default
        #line hidden
        
        #line 153 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(serviceGuid));

        
        #line default
        #line hidden
        
        #line 153 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"
this.Write("}\" />\r\n");

        
        #line default
        #line hidden
        
        #line 154 "D:\CVUT\dnWalker\dnWalker.TestGenerator\XunitFramework\XunitTestProjectTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal class XunitTestProjectTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
