//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnWalker.Parameters.Tests.Xml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnWalker.Parameters.Tests.Xml.XmlTexts", typeof(XmlTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Object Type=&quot;MyNamespace.MyClass&quot; Name=&quot;My:Namespace:My:Class&quot; IsNull=&quot;true&quot; /&gt;.
        /// </summary>
        internal static string ObjectParameter_IsNull {
            get {
                return ResourceManager.GetString("ObjectParameter_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Object Type=&quot;MyNamespace.MyClass&quot; Name=&quot;My:Namespace:My:Class&quot; IsNull=&quot;false&quot; /&gt;.
        /// </summary>
        internal static string ObjectParameter_NotNull_NoFields {
            get {
                return ResourceManager.GetString("ObjectParameter_NotNull_NoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Object Type=&quot;MyNamespace.MyClass&quot; Name=&quot;My:Namespace:My:Class&quot; IsNull=&quot;false&quot;&gt;
        ///  &lt;Field Name=&quot;My_Field&quot;&gt;
        ///    &lt;PrimitiveValue Type=&quot;System.Int32&quot; Name=&quot;My:Namespace:My:Class:My_Field&quot;&gt;-5&lt;/PrimitiveValue&gt;
        ///  &lt;/Field&gt;
        ///&lt;/Object&gt;.
        /// </summary>
        internal static string ObjectParameter_NotNull_SomeFields {
            get {
                return ResourceManager.GetString("ObjectParameter_NotNull_SomeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Object Type=&quot;MyNamespace.MyClass&quot; Name=&quot;My:Namespace:My:Class&quot; IsNull=&quot;false&quot;&gt;
        ///  &lt;Field Name=&quot;My_Field&quot;&gt;
        ///    &lt;PrimitiveValue Type=&quot;System.Int32&quot; Name=&quot;My:Namespace:My:Class:My_Field&quot;&gt;-5&lt;/PrimitiveValue&gt;
        ///  &lt;/Field&gt;
        ///  &lt;Field Name=&quot;My_ComplexField&quot;&gt;
        ///    &lt;Object Type=&quot;MyNamespace.AnotherClass&quot; Name=&quot;My:Namespace:My:Class:My_ComplexField&quot; IsNull=&quot;false&quot; /&gt;
        ///  &lt;/Field&gt;
        ///&lt;/Object&gt;.
        /// </summary>
        internal static string ObjectParameter_NotNull_SomeFiObjectParameter_NotNull_PrimitiveFields_ComplexField {
            get {
                return ResourceManager.GetString("ObjectParameter_NotNull_SomeFiObjectParameter_NotNull_PrimitiveFields_ComplexFiel" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PrimitiveValue Type=&quot;{0}&quot; Name=&quot;{1}&quot;&gt;{2}&lt;/PrimitiveValue&gt;.
        /// </summary>
        internal static string PrimitiveValueFormat {
            get {
                return ResourceManager.GetString("PrimitiveValueFormat", resourceCulture);
            }
        }
    }
}
