// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dnWalker.TestGenerator.XunitProvider
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using dnWalker.TestGenerator.Templates;
    using dnWalker.TestGenerator.TestClasses;
    using dnWalker.TestGenerator.TestClasses.Schemas;
    using dnWalker.TestGenerator.TestFrameworks;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class XunitTestClassTemplate : dnWalker.TestGenerator.TestClasses.TestClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 11 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            // generate usings

            
            #line default
            #line hidden
            
            #line 14 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            foreach (IEnumerable<string> nsGroup in GetNamespaces())
            {
                foreach (string ns in nsGroup)
                {
 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 20 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 21 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            }
 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 25 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

        }
 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 29 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            // declare test namespace

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 32 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.TestNamespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 34 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            // declare test class

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 37 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.TestClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\r\n");
            
            #line 40 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            // for each schema create a method

            
            #line default
            #line hidden
            
            #line 43 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            foreach (TestSchema schema in Context.GetSchemas())
            {
 
            
            #line default
            #line hidden
            this.Write("        public void ");
            
            #line 47 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.TestMethodName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n");
            
            #line 49 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

                PushIndent();
                PushIndent();
                PushIndent();
                schema.Write(this, TemplateProvider);
                PopIndent();
                PopIndent();
                PopIndent();
 
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 59 "D:\CVUT\dnWalker\dnWalker.TestGenerator.XunitProvider\XunitTestClassTemplate.tt"

            }
 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
