//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnWalker.TestGenerator.XunitProvider {
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using dnWalker.TestGenerator.Templates;
    using dnWalker.TestGenerator.TestClasses;
    using dnWalker.TestGenerator.TestClasses.Schemas;
    using dnWalker.TestGenerator.TestFrameworks;
    
    
    internal partial class XunitTestClassTemplate : dnWalker.TestGenerator.TestClasses.TestClassTemplateBase {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 11 ""

            // generate usings

            
            #line default
            #line hidden
            
            #line 14 ""

            foreach (IEnumerable<string> nsGroup in GetNamespaces())
            {
                foreach (string ns in nsGroup)
                {
 
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("using ");
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( ns ));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 21 ""

            }
 
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 25 ""

        }
 
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 29 ""

            // declare test namespace

            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write("namespace ");
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.TestNamespaceName ));
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write("\n{\n");
            
            #line default
            #line hidden
            
            #line 34 ""

            // declare test class

            
            #line default
            #line hidden
            
            #line 37 ""
            this.Write("    public class ");
            
            #line default
            #line hidden
            
            #line 37 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.TestClassName ));
            
            #line default
            #line hidden
            
            #line 37 ""
            this.Write("\n    {\n\n");
            
            #line default
            #line hidden
            
            #line 40 ""

            // for each schema create a method

            
            #line default
            #line hidden
            
            #line 43 ""

            foreach (TestSchema schema in Context.GetSchemas())
            {
 
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("        public void ");
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( schema.TestMethodName ));
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("()\n        {\n");
            
            #line default
            #line hidden
            
            #line 49 ""

                schema.Write(this, TemplateProvider);
 
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write("        }\n");
            
            #line default
            #line hidden
            
            #line 53 ""

            }
 
            
            #line default
            #line hidden
            
            #line 56 ""
            this.Write("    }\n}\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
