// This file was generated by dnWalker.TestGenerator tool 01. 01. 2022 - 22:25:15
#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using FluentAssertions;

using Xunit;

using Moq;

namespace Examples.Concolic.Features.Objects.Tests
{
	public class MethodsWithObjectParameter_Tests_AbstractClass_AbstractMethod
	{
		#region Test Methods

		[Fact]
		public void Test_Iteration_1()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.AbstractClass? var_0x00000005 = null;
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.AbstractClass_AbstractMethod(var_0x00000005);
		}

		[Fact]
		public void Test_Iteration_2()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.AbstractClass? var_0x00000005 = Create_0x00000005(out Mock<Examples.Concolic.Features.Objects.AbstractClass> methodsMock_0x00000005);
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.AbstractClass_AbstractMethod(var_0x00000005);
		}

		[Fact]
		public void Test_Iteration_3()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.AbstractClass? var_0x00000005 = Create_0x00000005(out Mock<Examples.Concolic.Features.Objects.AbstractClass> methodsMock_0x00000005);
			
			Examples.Concolic.Features.Objects.TestClass? var_0x00000007 = Create_0x00000007(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x00000007);
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			InitializeMethods_0x00000005
			(
				methodsMock_0x00000005,
				arg_AbstractMethod: new Examples.Concolic.Features.Objects.TestClass[] {  var_0x00000007 } 
			);
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.AbstractClass_AbstractMethod(var_0x00000005);
		}

		[Fact]
		public void Test_Iteration_4()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.AbstractClass? var_0x00000005 = Create_0x00000005(out Mock<Examples.Concolic.Features.Objects.AbstractClass> methodsMock_0x00000005);
			
			Examples.Concolic.Features.Objects.TestClass? var_0x00000007 = Create_0x00000007(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x00000007);
			
			System.Double var_0x00000009 = 0;
			
			Examples.Concolic.Features.Objects.TestClass? var_0x0000000A = Create_0x0000000A(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x0000000A);
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			InitializeMethods_0x00000005
			(
				methodsMock_0x00000005,
				arg_AbstractMethod: new Examples.Concolic.Features.Objects.TestClass[] {  var_0x00000007, var_0x0000000A } 
			);
			InitializeFields_0x00000007
			(
				var_0x00000007,
				arg_OtherField: var_0x00000009
			);

			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.AbstractClass_AbstractMethod(var_0x00000005);
		}

		[Fact]
		public void Test_Iteration_5()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.AbstractClass? var_0x00000005 = Create_0x00000005(out Mock<Examples.Concolic.Features.Objects.AbstractClass> methodsMock_0x00000005);
			
			Examples.Concolic.Features.Objects.TestClass? var_0x00000007 = Create_0x00000007(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x00000007);
			
			System.Double var_0x00000009 = 0;
			
			Examples.Concolic.Features.Objects.TestClass? var_0x0000000A = Create_0x0000000A(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x0000000A);
			
			System.Double var_0x0000000C = 6;
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			InitializeMethods_0x00000005
			(
				methodsMock_0x00000005,
				arg_AbstractMethod: new Examples.Concolic.Features.Objects.TestClass[] {  var_0x00000007, var_0x0000000A } 
			);
			InitializeFields_0x00000007
			(
				var_0x00000007,
				arg_OtherField: var_0x00000009
			);

			InitializeFields_0x0000000A
			(
				var_0x0000000A,
				arg_OtherField: var_0x0000000C
			);

			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.AbstractClass_AbstractMethod(var_0x00000005);
		}

		[Fact]
		public void Test_Iteration_6()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.AbstractClass? var_0x00000005 = Create_0x00000005(out Mock<Examples.Concolic.Features.Objects.AbstractClass> methodsMock_0x00000005);
			
			Examples.Concolic.Features.Objects.TestClass? var_0x00000007 = Create_0x00000007(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x00000007);
			
			System.Double var_0x00000009 = 5;
			
			Examples.Concolic.Features.Objects.TestClass? var_0x0000000A = Create_0x0000000A(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x0000000A);
			
			System.Double var_0x0000000C = 6;
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			InitializeMethods_0x00000005
			(
				methodsMock_0x00000005,
				arg_AbstractMethod: new Examples.Concolic.Features.Objects.TestClass[] {  var_0x00000007, var_0x0000000A } 
			);
			InitializeFields_0x00000007
			(
				var_0x00000007,
				arg_OtherField: var_0x00000009
			);

			InitializeFields_0x0000000A
			(
				var_0x0000000A,
				arg_OtherField: var_0x0000000C
			);

			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.AbstractClass_AbstractMethod(var_0x00000005);
		}
		#endregion Test Methods

		#region Parameter Creation Methods
		// these methods constructs instances of parameters along with interfaces for their initialization
		private Examples.Concolic.Features.Objects.AbstractClass Create_0x00000005(out Mock<Examples.Concolic.Features.Objects.AbstractClass> methodsMock)
		{
			methodsMock = new Mock<Examples.Concolic.Features.Objects.AbstractClass>();
			var instance = methodsMock.Object;
			return instance;
		}
		
		private Examples.Concolic.Features.Objects.TestClass Create_0x00000007(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock)
		{
			methodsMock = new Mock<Examples.Concolic.Features.Objects.TestClass>();
			var instance = methodsMock.Object;
			return instance;
		}
		
		private Examples.Concolic.Features.Objects.TestClass Create_0x0000000A(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock)
		{
			methodsMock = new Mock<Examples.Concolic.Features.Objects.TestClass>();
			var instance = methodsMock.Object;
			return instance;
		}
		


		#endregion Parameter Creation Methods

		#region Parameter Initialization Methods
		// initialize parameter 0x00000005
		// - instance
		private void InitializeMethods_0x00000005(Mock<Examples.Concolic.Features.Objects.AbstractClass> mock, Examples.Concolic.Features.Objects.TestClass[] arg_AbstractMethod = default)
		{
			// TODO: initialize method results to correspond to provided values
			// first invocation returns arg_<MethodName>[0] etc
			// right now, always return first element... :(
			mock.Setup(o => o.AbstractMethod()).Returns(arg_AbstractMethod[0]);
		}
		// initialize parameter 0x00000007
		// - 
		private void InitializeFields_0x00000007(Examples.Concolic.Features.Objects.TestClass instance, System.Double arg_OtherField = default)
		{
			// initialize field using private object
			instance.SetPrivate("OtherField", arg_OtherField);
		}
		// initialize parameter 0x0000000A
		// - 
		private void InitializeFields_0x0000000A(Examples.Concolic.Features.Objects.TestClass instance, System.Double arg_OtherField = default)
		{
			// initialize field using private object
			instance.SetPrivate("OtherField", arg_OtherField);
		}
		#endregion Parameter Initialization Methods
	}
}


