// This file was generated by dnWalker.TestGenerator tool 08. 01. 2022 - 23:46:56
#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using FluentAssertions;

using Xunit;

using Moq;

namespace Examples.Concolic.Features.ReturnValue.Tests
{
	public class MethodsWithReturnValue_Tests_GetSumIfTrueDiffIfFalse
	{
		#region Test Methods

		[Fact]
		public void Test_Iteration_1()
		{
			// construct all input parameters which are used in the test
			// TODO: construct return value comparer instance
			System.Int32 var_0x00000001 =  default(System.Int32) ;
			
			System.Int32 var_0x00000002 =  default(System.Int32) ;
			
			System.Boolean var_0x00000003 =  default(System.Boolean) ;
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			var result = Examples.Concolic.Features.ReturnValue.MethodsWithReturnValue.GetSumIfTrueDiffIfFalse(var_0x00000001, var_0x00000002, var_0x00000003);

			// construct all output parameters which are used in the test
			// 1. ret val if exists
			System.Int32  retVal_0x00000004 = 0;

			Assert.Equal(result, retVal_0x00000004);


		}

		[Fact]
		public void Test_Iteration_2()
		{
			// construct all input parameters which are used in the test
			// TODO: construct return value comparer instance
			System.Int32 var_0x00000001 =  default(System.Int32) ;
			
			System.Int32 var_0x00000002 =  default(System.Int32) ;
			
			System.Boolean var_0x00000003 = true;
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			var result = Examples.Concolic.Features.ReturnValue.MethodsWithReturnValue.GetSumIfTrueDiffIfFalse(var_0x00000001, var_0x00000002, var_0x00000003);

			// construct all output parameters which are used in the test
			// 1. ret val if exists
			System.Int32  retVal_0x00000005 = 0;

			Assert.Equal(result, retVal_0x00000005);


		}
		#endregion Test Methods

		#region Parameter Creation Methods
		// these methods constructs instances of parameters along with interfaces for their initialization


		#endregion Parameter Creation Methods

		#region Parameter Initialization Methods
		#endregion Parameter Initialization Methods
	}
}


