// This file was generated by dnWalker.TestGenerator tool 01. 01. 2022 - 22:53:50
#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using FluentAssertions;

using Xunit;

using Moq;

namespace Examples.Concolic.Features.Objects.Tests
{
	public class MethodsWithObjectParameter_Tests_BranchIfNotNull
	{
		#region Test Methods

		[Fact]
		public void Test_Iteration_1()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.TestClass? var_0x00000014 = null;
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.BranchIfNotNull(var_0x00000014);
		}

		[Fact]
		public void Test_Iteration_2()
		{
			// construct all parameters which are used in the test
			// TODO: construct return value comparer instance
			Examples.Concolic.Features.Objects.TestClass? var_0x00000014 = Create_0x00000014(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock_0x00000014);
			
			// initialize all parameters which needs initialization
			// TODO: initialize return value comparer instance
			
			// execute the tested method
			// TODO: make assert for method exception
			// TODO: make assert for method return values
			// TODO: handle instance methods
			Examples.Concolic.Features.Objects.MethodsWithObjectParameter.BranchIfNotNull(var_0x00000014);
		}
		#endregion Test Methods

		#region Parameter Creation Methods
		// these methods constructs instances of parameters along with interfaces for their initialization
		private Examples.Concolic.Features.Objects.TestClass Create_0x00000014(out Mock<Examples.Concolic.Features.Objects.TestClass> methodsMock)
		{
			methodsMock = new Mock<Examples.Concolic.Features.Objects.TestClass>();
			var instance = methodsMock.Object;
			return instance;
		}
		


		#endregion Parameter Creation Methods

		#region Parameter Initialization Methods
		// initialize parameter 0x00000014
		// - instance
		#endregion Parameter Initialization Methods
	}
}


