// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dnWalker.TestGenerator.TestProjects
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class TestProjectTemplate : Templates.TemplateBase<ITestProjectContext>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
 ITestProjectContext context = Context; 
            
            #line default
            #line hidden
            this.Write("<Project Sdk=\"Microsoft.NET.Sdk\">\r\n\r\n    <PropertyGroup>\r\n");
            
            #line 10 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	if (context.Targets.Count == 0)
	{

            
            #line default
            #line hidden
            this.Write("        <TargetFramework>net6.0</TargetFramework>\r\n");
            
            #line 15 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}
	else if (Context.Targets.Count == 1)
	{

            
            #line default
            #line hidden
            this.Write("        <TargetFramework>");
            
            #line 20 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(context.Targets[0]));
            
            #line default
            #line hidden
            this.Write("</TargetFramework>\r\n");
            
            #line 21 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("        <TargetFrameworks>");
            
            #line 26 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(context.Targets)));
            
            #line default
            #line hidden
            this.Write("</TargetFrameworks>\r\n");
            
            #line 27 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("        <IsPackable>false</IsPackable>\r\n        <Nullable>");
            
            #line 31 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(context.NullableEnable ? "enable" : "disable"));
            
            #line default
            #line hidden
            this.Write("</Nullable>\r\n    </PropertyGroup>\r\n\r\n");
            
            #line 34 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
 
	// package references 
	if (context.PackageReferencies.Count > 0)
	{

            
            #line default
            #line hidden
            this.Write("    <ItemGroup>\r\n");
            
            #line 40 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

		foreach (PackageReference p in context.PackageReferencies)
		{
			WritePackageReference(p);
		}

            
            #line default
            #line hidden
            this.Write("    </ItemGroup>\r\n\r\n");
            
            #line 48 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}

	// project references
	if (context.ProjectReferencies.Count > 0)
	{

            
            #line default
            #line hidden
            this.Write("    <ItemGroup>\r\n");
            
            #line 56 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

		foreach (string project in context.ProjectReferencies)
		{
			WriteProjectReference(project);
		}

            
            #line default
            #line hidden
            this.Write("    </ItemGroup>\r\n\r\n");
            
            #line 64 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}
	// service references
	if (context.Services.Count > 0)
	{

            
            #line default
            #line hidden
            this.Write("    <ItemGroup>\r\n");
            
            #line 71 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

		foreach (Guid s in context.Services)
		{
			WriteServiceReference(s);
		}

            
            #line default
            #line hidden
            this.Write("    </ItemGroup>\r\n");
            
            #line 78 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("</Project>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 82 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	private static string JoinTokens(IEnumerable<string> tokens)
	{
		return string.Join("; ", tokens);
	}

        
        #line default
        #line hidden
        
        #line 88 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	private void WritePackageReference(PackageReference p)
	{

        
        #line default
        #line hidden
        
        #line 91 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("        <PackageReference Include=\"");

        
        #line default
        #line hidden
        
        #line 92 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 92 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("\" Version=\"");

        
        #line default
        #line hidden
        
        #line 92 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Version));

        
        #line default
        #line hidden
        
        #line 92 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("\"");

        
        #line default
        #line hidden
        
        #line 92 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

		if (p.IncludeAssets.Count > 0 || p.ExcludeAssets.Count > 0 || p.PrivateAssets.Count > 0)
		{

        
        #line default
        #line hidden
        
        #line 95 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(">\r\n");

        
        #line default
        #line hidden
        
        #line 96 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

			if (p.IncludeAssets.Count > 0)
			{

        
        #line default
        #line hidden
        
        #line 99 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("            <IncludeAssets>");

        
        #line default
        #line hidden
        
        #line 100 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(p.IncludeAssets)));

        
        #line default
        #line hidden
        
        #line 100 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("</IncludeAssets>\r\n");

        
        #line default
        #line hidden
        
        #line 101 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

			}
			if (p.ExcludeAssets.Count > 0)
			{

        
        #line default
        #line hidden
        
        #line 105 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("            <ExcludeAssets>");

        
        #line default
        #line hidden
        
        #line 106 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(p.ExcludeAssets)));

        
        #line default
        #line hidden
        
        #line 106 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("</ExcludeAssets>\r\n");

        
        #line default
        #line hidden
        
        #line 107 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

			}
			if (p.PrivateAssets.Count > 0)
			{

        
        #line default
        #line hidden
        
        #line 111 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("            <PrivateAssets>");

        
        #line default
        #line hidden
        
        #line 112 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(JoinTokens(p.PrivateAssets)));

        
        #line default
        #line hidden
        
        #line 112 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("</PrivateAssets>\r\n");

        
        #line default
        #line hidden
        
        #line 113 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

			}

        
        #line default
        #line hidden
        
        #line 115 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("        </PackageReference>\r\n");

        
        #line default
        #line hidden
        
        #line 117 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

		}
		else
		{

        
        #line default
        #line hidden
        
        #line 121 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(" />\r\n");

        
        #line default
        #line hidden
        
        #line 122 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

		}
	}

        
        #line default
        #line hidden
        
        #line 126 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	private void WriteProjectReference(string project)
	{

        
        #line default
        #line hidden
        
        #line 129 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("        <ProjectReference Include=\"");

        
        #line default
        #line hidden
        
        #line 130 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(project));

        
        #line default
        #line hidden
        
        #line 130 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("\" />\r\n");

        
        #line default
        #line hidden
        
        #line 131 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}

        
        #line default
        #line hidden
        
        #line 134 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	private void WriteServiceReference(Guid serviceGuid)
	{

        
        #line default
        #line hidden
        
        #line 137 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("        <Service Include=\"{");

        
        #line default
        #line hidden
        
        #line 138 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(serviceGuid));

        
        #line default
        #line hidden
        
        #line 138 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"
this.Write("}\" />\r\n");

        
        #line default
        #line hidden
        
        #line 139 "D:\CVUT\dnWalker\dnWalker.TestGenerator\TestProjects\TestProjectTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
