//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnWalker.TestGenerator.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnWalker.TestGenerator.Tests.CodeTexts", typeof(CodeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 5;
        ///.
        /// </summary>
        internal static string Assign_5_To_X {
            get {
                return ResourceManager.GetString("Assign_5_To_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class MyClass
        ///{
        ///    public void MyMethod()
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Declare_Class_WithMethod {
            get {
                return ResourceManager.GetString("Declare_Class_WithMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class MyClass
        ///{
        ///    public void MyMethod()
        ///    {
        ///        int x = 5;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Declare_Class_WithMethod_WithVariable {
            get {
                return ResourceManager.GetString("Declare_Class_WithMethod_WithVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class MyClass
        ///{
        ///}
        ///.
        /// </summary>
        internal static string Declare_Empty_Class {
            get {
                return ResourceManager.GetString("Declare_Empty_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int x = 5;
        ///.
        /// </summary>
        internal static string Declare_X_WithInitialValue {
            get {
                return ResourceManager.GetString("Declare_X_WithInitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int x;
        ///.
        /// </summary>
        internal static string Declare_X_WithoutInitialValue {
            get {
                return ResourceManager.GetString("Declare_X_WithoutInitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///.
        /// </summary>
        internal static string Using_System {
            get {
                return ResourceManager.GetString("Using_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MyAttribute]
        ///.
        /// </summary>
        internal static string WriteAttribute {
            get {
                return ResourceManager.GetString("WriteAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MyAttribute(true, 5)]
        ///.
        /// </summary>
        internal static string WriteAttribute_WithArguments {
            get {
                return ResourceManager.GetString("WriteAttribute_WithArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MyAttribute(&quot;some text&quot;, SomeBooleanProperty = false, SomeIntProperty = 10)]
        ///.
        /// </summary>
        internal static string WriteAttribute_WithArgumentsAndParameters {
            get {
                return ResourceManager.GetString("WriteAttribute_WithArgumentsAndParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MyAttribute(SomeBooleanProperty = false, SomeIntProperty = 10)]
        ///.
        /// </summary>
        internal static string WriteAttribute_WithParameters {
            get {
                return ResourceManager.GetString("WriteAttribute_WithParameters", resourceCulture);
            }
        }
    }
}
